### PR TITLE
do not integrate flow features if flow_loss is disabled

### PR DESCRIPTION
**Pull request by martinmeinke**
Thank you for a great project and interesting read.

While playing around with the implementation, I noticed this. Not sure If I misunderstood the intent, but it seems that dynamic features don't need to be integrated if `flow_loss` is disabled.

### CODE REVIEW

**Comment by dyfcalid** [comment]
😊Thank you very much for your interest and implementation! However, even without using flow loss, the model is able to learn how to integrate dynamic features on its own, and the gradients can be back-propagated properly. Flow loss just provides additional constraints based on point clouds. If you have further questions, please feel free to contact me. Thanks again for your efforts!

**Comment by martinmeinke** [comment]
Ahh - thank you for the explanation! That sounds plausible.

Did you by any chance evaluate the benefit of enabling the `flow_loss` by any chance?
I tried to visualize the flow-net predictions, but they didn't seem to converge to plausible results (using the default optimizer parameters).

(left: cloud with intensity / right: fwd. flow prediction)
image

Why I am interested in your work:
I have been doing some work on scene flow estimation lately, building on some of the Neural Scene Flow Prior line of research. Your project seems like a nice sandbox for experimenting with turning the "implicit" motion estimation information encoded in your network into "explicit" scene flow information.

**Comment by dyfcalid** [comment]
Hi, thank you for your question. 😀
Actually, we have tried some methods to encode the flow before, but it is still a challenge for long sequences. And since NeRF samples points in the whole space, it also needs to consider points beyond the point cloud. And some methods like Neural Scene Flow Prior may not handle it well. Thus, we combine the flow net with the whole framework for end-to-end optimization (like deformable NeRFs), as a way to indirectly improve the final performance. But the "implicit" results largely depend on the optimization and may not be in line with the explicit scene flow. 
It remains future work, and we are working on it. The current released version of the flow net is just a baseline with simplicity and generality, and we'll have some updates soon to improve this performance. Stay tuned!
In addition, decoupling the scene flow explicitly and making it a two-stage optimization is also a promising direction. But again, there may be problems as mentioned above. If you have some good experimental results, you can share them here if you'd like, and I'm looking forward to it. 👏

**Comment by martinmeinke** [comment]
Thank you for your assessment - I might do some further experimentation down the line and will keep you posted if I encounter something interesting!

**Comment by dyfcalid** [comment]
Hi, there.
There have been some recent updates, which may help to achieve better flow prediction.

**Pull request closed without merging**
